### ISSUE TITLE
Correct Errors in Contribution Guidelines

### ISSUE THREAD

**Issue by Sammybams** [mlsanigeria/AI-Hacktober-MLSA#11]
### 👋 Hello Contributors!

To maintain the quality of our documentation and resources, we need your help to spot and correct errors in our Contribution Guidelines. This will ensure that our guidelines are clear, concise, and accurate for all contributors.

#### How You Can Help:
1. Review the Contribution Guidelines: Take a close look at the [Contribution Guidelines](https://github.com/mlsanigeria/AI-Hacktober-MLSA/blob/main/CONTRIBUTING.md) document in the repository.
2. Identify Errors: Carefully identify any spelling errors, grammatical mistakes, or inaccuracies within the document.
3. Propose Corrections: Suggest corrections for the errors you find. You can use inline comments or submit a pull request with the changes.

#### Example:
If you find a sentence like this:

```arduino
"We welcoming all contributions."
```
Please suggest/make the correction:

```arduino
"We welcome all contributions."
```

**Create a Pull Request**: Once you've identified and corrected the errors, create a pull request with your changes. Follow our guidelines for submitting pull requests, as outlined in the Contribution Guidelines.

Happy error-spotting and correcting! 📝🚀

**Comment by Rathish-Rajendran** [comment]
Hi, The link is broken!

**Comment by Sammybams** [comment]
> Hi, The link is broken!
@Rathish-Rajendran 
Oh sorry, thank you for pointing this out. We have fixed it now.

**Comment by Rathish-Rajendran** [comment]
Thanks for fixing the link. I would like to work on this issue. Can you kindly assign this issue to me?

**Comment by Sammybams** [comment]
> Thanks for fixing the link. I would like to work on this issue. Can you kindly assign this issue to me?
@Rathish-Rajendran 
The issue is open to anyone to work on. So you can go ahead and do so.
We would also recommend that you wait till October 1, so your contributions can count towards Hactoberfeset as this is the motive behind creating this repository.

**Comment by Rathish-Rajendran** [comment]
> > Thanks for fixing the link. I would like to work on this issue. Can you kindly assign this issue to me?
> > @Rathish-Rajendran
> > The issue is open to anyone to work on. So you can go ahead and do so.
> > We would also recommend that you wait till October 1, so your contributions can count towards Hactoberfeset as this is the motive behind creating this repository.

@Sammybams Thanks!
Will give a pull request post October 1, 2023.

**Comment by Sammybams** [comment]
Thank you @Rathish-Rajendran. Looking forward to it.

**Comment by Rathish-Rajendran** [comment]
Hi @Sammybams , I have resolved all the grammatical issues and some punctual issues in the CONTRIBUTING.md file in this PR #134 .
Kindly take a look at them and merge them up if you are okay with the changes and please don't forget to add the "hacktoberfest-accepted" label.
Thanks!
