### ISSUE TITLE
Project 3: Data Preprocessing Phase

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/AI-Hacktober-MLSA#177]
There is a slight issue with the ordinal encoding for the WAEC grades.
This is what is found in the file.
```
# Ordinal encoding map
ordinal_encoding_map = {'A': 5, 'B': 4, 'C': 3, 'D': 2, 'E': 1, 'F': 6}
```
**The value for 'F" is inputted as 6 instead of 0**

If you agree with me, I would love to solve the issue.

**Comment by Sammybams** [comment]
Thank you @Odeyiany2 for pointing this out. You can go ahead to modify the starter notebook as regards this.
You can, alongside, create your own folder and notebook for experimentation following the naming convention in our contribution guidelines.

**Comment by Odeyiany2** [comment]
Okay @Sammybams I'll do that. Thank you.
