### ISSUE TITLE
Create Model Folder 

### ISSUE THREAD

**Issue by Winonymous** [mlsanigeria/AI-Hacktober-MLSA#184]
Can we create a model folder for the image classification model where we can store all the models trained.

**Comment by Sammybams** [comment]
That was an option we considered but looking at the fact that models could get really large and when you want to pull changes from the repo, you would pull these files and it could load up your data and storage, so we decided against it.

So what can be done is to probably upload your model to the cloud (Google Drive, OneDrive, etc.) and add the link to it in your notebook. So we can retrieve from there and run tests. And finally, fully retrieve if it's the best model, for deployment.

**Comment by Pratikdate** [comment]
Assigned me I will maintain models folder

**Comment by Sammybams** [comment]
> Assigned me I will maintain models folder
Thank you @Pratikdate, but we are not saving the models in a folder. Thank you.
