### ISSUE TITLE
[SUGGESTED FEATURE REQUEST]: Additional Link under the Resource Section in the Contributing File

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/AI-Hacktober-MLSA#249]
**Context:**
I would like to add an additional link (YouTube video) to the resources under the contributing file.

**Has the feature been requested before?**
No it hasn't

**Describe the solution you'd like**
Looking at the resources for project two, I wasn't quite sure where to start because I was new to Azure services. I believe adding a link to the session conducted for project 2 will give a new contributor (who is new to Microsoft Azure services) and idea on how to start and will serve as a proper support to the previous links on documentation.

**If the feature request is approved, would you be willing to work on it and submit a PR?**
Yes

**Comment by Sammybams** [comment]
Okay nice. Thank you for bringing this up, you can go ahead and add it @Odeyiany2.
